# Generated by Django 6.0.2 on 2026-02-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='established',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
    ]
