# Generated by Django 6.0.2 on 2026-02-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otprecord_registrationrequest_faculty_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
