# Generated by Django 6.0.2 on 2026-03-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_otprecord_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='generated_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='generated_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
