# Generated by Django 6.0.2 on 2026-03-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_facultyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allocated_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_courses', to='api.faculty'),
        ),
    ]
