# Generated by Django 6.0.2 on 2026-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_allocated_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='google_form_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
