# Generated by Django 6.0.2 on 2026-03-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_exam_google_form_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fee',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='installment_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fee',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
