# Generated by Django 6.0.2 on 2026-03-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_course_semester_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_acknowledgments', to='api.faculty')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='api.notice')),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'unique_together': {('notice', 'faculty')},
            },
        ),
    ]
